### ISSUE TITLE
CI failures after adding a gccgo test environment

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1078]
After PR #1071 was merged we started seeing failures such as [this](https://github.com/elves/elvish/pull/1077/checks?check_run_id=888354728). That PR was based on the master branch plus a trivial comment. The error in each case looks like this:

```
/usr/bin/ld: $WORK/b057/_pkg_.a(_go_.o): in function `github.x2ecom..z2felves..z2felvish..z2fpkg..z2fcli..z2faddons..z2fhistwalk.Prev':
/tmp/cirrus-ci-build/pkg/edit/ /tmp/cirrus-ci-build/pkg/cli/addons/histwalk/histwalk.go:86: undefined reference to `github.x2ecom..z2felves..z2felvish..z2fpkg..z2fcli..z2faddons..z2fhistwalk.github.x2ecom..z2felves..z2felvish..z2fpkg..z2fcli..z2faddons..z2fhistwalk..thunk1..f'
/usr/bin/ld: /tmp/cirrus-ci-build/pkg/edit/ /tmp/cirrus-ci-build/pkg/cli/addons/histwalk/histwalk.go:86: undefined reference to `github.x2ecom..z2felves..z2felvish..z2fpkg..z2fcli..z2faddons..z2fhistwalk.github.x2ecom..z2felves..z2felvish..z2fpkg..z2fcli..z2faddons..z2fhistwalk..thunk0..f'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

**Comment by krader1961** [comment]
@zhsj, Since you authored the change to the CI configuration that added support for testing builds using gccgo you're probably the person in the best position to debug this problem.

**Comment by zhsj** [comment]
This is caused by https://github.com/elves/elvish/commit/3501b945aa9f41a4c27d1695a51eb720a60ebaf3 which triggers a gcc bug https://github.com/golang/go/issues/40252

**Comment by krader1961** [comment]
Thanks for being proactive, @zhsj, in already reporting this to the Go team. Does this mean that building elvish from git master now fails on Debian using gccgo? That is, not just in the CI test environment? If so should the problematic commit be reverted in whole or part? If not is there something we can do to make this work on the CI gccgo environment? Otherwise I think the CI gccgo environment needs to be disabled until the underlying problem is resolved. People contributing changes shouldn't have to wonder if their change broke the build.
