### PR TITLE
Tell external cmds to ignore job control signals

### LINKED ISSUE #988: suspending external command with [ctrl-z] does not yield a shell prompt
Using elvish built from HEAD run `vim` then press [ctrl-z]. The vim process is apparently suspended but the elvish process doesn't provide a new prompt. Typing is echoed but commands aren't executed. Sending SIGUSR1 results in the following stack dumps. I can reproduce on macOS and Linux.

```
goroutine 5 [running]:
github.com/elves/elvish/pkg/sys.DumpStack(0xc0001922d0, 0x15d49c8)
        /Users/krader/projects/3rd-party/elvish/pkg/sys/dumpstack.go:10 +0x9d
github.com/elves/elvish/pkg/program/shell.handleSignal(0x1672de0, 0xc000026660, 0xc0000a2010)
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell/signal_unix.go:19 +0x6b
github.com/elves/elvish/pkg/program/shell.setupShell.func1(0xc0001b6120, 0xc0000a2000, 0xc0000a2008, 0xc0000a2010)
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell/shell.go:28 +0xb0
created by github.com/elves/elvish/pkg/program/shell.setupShell
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell/shell.go:25 +0x12d

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000196c88)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000196c80)
        /usr/local/Cellar/go/1.14.1/libexec/src/sync/waitgroup.go:130 +0x64
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke(0xc000697220, 0xc000697270, 0xc0007af5e8, 0x100e856)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:173 +0x4c9
github.com/elves/elvish/pkg/eval.effectOp.exec(0x166ba00, 0xc000697220, 0x0, 0x3, 0xc000697270, 0x0, 0xc000200050)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:32 +0x69
github.com/elves/elvish/pkg/eval.chunkOp.invoke(0xc000b101a0, 0x1, 0x1, 0xc000697270, 0xc000b102c0, 0xc0007af6b0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:29 +0x7e
github.com/elves/elvish/pkg/eval.effectOp.exec(0x166c9a0, 0xc000b10200, 0x0, 0x3, 0xc000697270, 0xc000b10240, 0xc000b10260)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:32 +0x69
github.com/elves/elvish/pkg/eval.(*Evaler).Eval(0xc0001ec000, 0x166c9a0, 0xc000b10200, 0x0, 0x3, 0xc000316060, 0xc000b10220, 0x3, 0x3, 0x15d3748, ...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/eval.go:281 +0x1e1
github.com/elves/elvish/pkg/program/shell.evalInTTY(0xc0001ec000, 0x166c9a0, 0xc000b10200, 0x0, 0x3, 0xc000316060, 0xc0000a2000, 0xc0000a2008, 0xc0000a2010, 0x0, ...)
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell/shell.go:43 +0x1b4
github.com/elves/elvish/pkg/program/shell.Interact(0xc0000a2000, 0xc0000a2008, 0xc0000a2010, 0xc00011bd88)
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell/interact.go:85 +0x965
github.com/elves/elvish/pkg/program.(*shellProgram).Main(0xc00018c840, 0xc0000a2000, 0xc0000a2008, 0xc0000a2010, 0xc000098190, 0x0, 0x0, 0xc00011bf18)
        /Users/krader/projects/3rd-party/elvish/pkg/program/shell.go:31 +0x27c
github.com/elves/elvish/pkg/program.Main(0xc0000a2000, 0xc0000a2008, 0xc0000a2010, 0xc000098190, 0x1, 0x1, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/program/program.go:103 +0x1c8
main.main()
        /Users/krader/projects/3rd-party/elvish/main.go:14 +0x69

goroutine 34 [chan receive]:
github.com/elves/elvish/pkg/eval.getBlackholeChan.func1(0xc0001b6060)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port.go:59 +0x47
created by github.com/elves/elvish/pkg/eval.getBlackholeChan
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port.go:58 +0x58

goroutine 35 [syscall]:
os/signal.signal_recv(0x1672de0)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
        /usr/local/Cellar/go/1.14.1/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /usr/local/Cellar/go/1.14.1/libexec/src/os/signal/signal.go:127 +0x44

goroutine 6 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0002841c0)
        /Users/krader/projects/3rd-party/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
        /Users/krader/projects/3rd-party/elvish/pkg/cli/prompt/prompt.go:70 +0x15f

goroutine 7 [chan receive]:
github.com/elves/elvish/pkg/cli/prompt.(*Prompt).loop(0xc0002842a0)
        /Users/krader/projects/3rd-party/elvish/pkg/cli/prompt/prompt.go:77 +0xc8
created by github.com/elves/elvish/pkg/cli/prompt.New
        /Users/krader/projects/3rd-party/elvish/pkg/cli/prompt/prompt.go:70 +0x15f

goroutine 15127 [chan receive]:
github.com/elves/elvish/pkg/eval.relayChanToFile(0xc0000a4e40, 0xc0000a2008, 0xc0005aa4c0, 0xc, 0xc000196bd4)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port_helper.go:47 +0x1ae
created by github.com/elves/elvish/pkg/eval.portsFromFiles
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port_helper.go:31 +0xfd

goroutine 15129 [select]:
github.com/elves/elvish/pkg/eval.ListenInterrupts.func1(0xc00008e0c0, 0xc00008e180, 0xc00008e1e0, 0xc00008e240)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/interrupts.go:46 +0xad
created by github.com/elves/elvish/pkg/eval.ListenInterrupts
        /Users/krader/projects/3rd-party/elvish/pkg/eval/interrupts.go:42 +0x143

goroutine 13879 [syscall]:
syscall.syscall6(0x107dbd0, 0xf99a, 0xc00025fa9c, 0x0, 0xc0008e8090, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0xf99a, 0xc00025fa9c, 0x0, 0xc0008e8090, 0x90, 0x1593fa0, 0x1)
        /usr/local/Cellar/go/1.14.1/libexec/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0xf99a, 0xc00025faec, 0x0, 0xc0008e8090, 0x37, 0xc0008db560, 0x6)
        /usr/local/Cellar/go/1.14.1/libexec/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc00018e330, 0x37, 0xc0008db560, 0x6)
        /usr/local/Cellar/go/1.14.1/libexec/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
        /usr/local/Cellar/go/1.14.1/libexec/src/os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc000230b80, 0x37, 0xc0008f4050, 0xc000281d80, 0x5, 0x8, 0xc0003df440, 0xc0002a5800, 0xc0004840a0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/external_cmd.go:91 +0x37e
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc0002fb5f0, 0xc0008f4050, 0x0, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:380 +0x8be
github.com/elves/elvish/pkg/eval.effectOp.exec(0x166b960, 0xc0002fb5f0, 0xe93, 0x1003, 0xc0008f4050, 0xffffffffffffffff, 0xffffffffffffffff)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:32 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0x166b960, 0xc0002fb5f0, 0xe93, 0x1003, 0xc0008f4050, 0xc000010de0, 0xc0009df700, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:136 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:135 +0x424

goroutine 15128 [chan receive]:
github.com/elves/elvish/pkg/eval.relayChanToFile(0xc000169740, 0xc0000a2010, 0xc0005aa4c0, 0xc, 0xc000196bd4)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port_helper.go:47 +0x1ae
created by github.com/elves/elvish/pkg/eval.portsFromFiles
        /Users/krader/projects/3rd-party/elvish/pkg/eval/port_helper.go:32 +0x150

goroutine 15130 [syscall]:
syscall.syscall6(0x107dbd0, 0xf99e, 0xc00005fa9c, 0x0, 0xc0008e8000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0xf99e, 0xc00005fa9c, 0x0, 0xc0008e8000, 0x90, 0x1593fa0, 0x1)
        /usr/local/Cellar/go/1.14.1/libexec/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0xf99e, 0xc00005faec, 0x0, 0xc0008e8000, 0x12, 0xc0003ce0d0, 0x1)
        /usr/local/Cellar/go/1.14.1/libexec/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0006f6120, 0x12, 0xc0003ce0d0, 0x1)
        /usr/local/Cellar/go/1.14.1/libexec/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
        /usr/local/Cellar/go/1.14.1/libexec/src/os/exec.go:125
github.com/elves/elvish/pkg/eval.ExternalCmd.Call(0xc00060e0d8, 0x3, 0xc0006972c0, 0x0, 0x0, 0x0, 0xc000316180, 0xc00060e0d8, 0x15a6d71)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/external_cmd.go:91 +0x37e
github.com/elves/elvish/pkg/eval.(*formOp).invoke(0xc0007bb040, 0xc0006972c0, 0x0, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:380 +0x8be
github.com/elves/elvish/pkg/eval.effectOp.exec(0x166b960, 0xc0007bb040, 0x0, 0x3, 0xc0006972c0, 0x14d9040, 0xc0008dd4d8)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/op.go:32 +0x69
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func1(0x166b960, 0xc0007bb040, 0x0, 0x3, 0xc0006972c0, 0xc0004dc030, 0xc000196c80, 0xc00060e000)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:136 +0x60
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:135 +0x424

goroutine 13880 [semacquire]:
sync.runtime_Semacquire(0xc0009df708)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0009df700)
        /usr/local/Cellar/go/1.14.1/libexec/src/sync/waitgroup.go:130 +0x64
github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke.func2(0xc0009df700, 0xc0008f4000, 0xc0002df630, 0xc000010de0, 0x1, 0x1)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:156 +0x40
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).invoke
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:155 +0x49d
```

### PR DESCRIPTION
**Pull request by krader1961**
Since elvish does not support job control it should run all external
commands with the tty job control signals set to be ignored. See "APUE",
third edition, page 379.

This doesn't actually fix the problem in the case of broken programs
like vim which blindly assume the parent process implements job control.
But there isn't much we can do about that other than try to get those
programs to pay attention to being told to ignore SIGTSTP.

Fixes #988

### CODE REVIEW

File: pkg/sys/signals_unix.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+func NotifySignals() chan os.Signal {
+	// This catches every signal regardless of whether it is ignored.
+	sigCh := make(chan os.Signal, sigsChanBufferSize)
+	signal.Notify(sigCh)
+	// TODO: Remove this if, and when, job control is implemented. This
+	// handles the case of running an external command from an interactive
+	// prompt.
+	//
+	// See https://github.com/elves/elvish/issues/988.
+	signal.Ignore(syscall.SIGTTIN, syscall.SIGTTOU, syscall.SIGTSTP)
```
Comment (xiaq) [inline pkg/sys/signals_unix.go:20]: Why is it necessary to do the `Ignore` call here, instead of in `setupShell`?

Comment (krader1961) [reply pkg/sys/signals_unix.go:20]: This is because `signal.Notify`, when called without any signals, catches every signal -- even if a signal is currently ignored. So we have to explicitly ignore the TTY signals after calling `signal.Notify` since elvish does not implement UNIX job control. This is done here because this function is called from two locations and might be called twice. Regardless of that happenstance we have to ignore TTY job control signals and do so in any child process that is launched.

Comment (xiaq) [reply pkg/sys/signals_unix.go:20]: Interesting, this is something worth documenting in the comment.

**Comment by xiaq** [comment]
Hmm, this broke build due to a missing import - fixed in 8995bc5663001055754eff7d0354e185146b708f. Unsure why this wasn't captured by CI...
